---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: "golang"
    tag: "1.8.3-jessie"

inputs:
- name: apt-package-resource

params:
  INPUT: apt-package-resource

run:
  path: ./apt-package-resource/ci/scripts/build.sh
