#!/bin/bash
set -o pipefail

exec 3>&1 # make stdout available as fd 3 for the result
exec 1>&2 # redirect all output to stderr for logging

# Read inputs
payload=$(mktemp "$TMPDIR/apt-package-resource-request.XXXXXX")
cat > "$payload" <&0

echo "$payload" >&2
