---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: "golang"
    tag: "1.8.3-jessie"

inputs:
- name: apt-package-resource

# outputs:
# - name: build-marketplace-api

params:
  INPUT: apt-package-resource
#   OUTPUT: build-marketplace-api

run:
  path: sh
  args:
    - -exec
    - |
      cd $INPUT
      make
